# Generated by Django 5.0.3 on 2024-03-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='nonn', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.CharField(default='nonn', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='class_year',
            field=models.CharField(default='nonn', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(default='nonn', max_length=100),
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league_app.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
