# Generated by Django 5.0.3 on 2024-03-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0002_remove_team_logo_player_position_team_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='class_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(max_length=100),
        ),
    ]
