# Generated by Django 5.0.3 on 2024-03-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0003_team_logo_alter_player_position_alter_team_captain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('week', models.IntegerField()),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
