# Generated by Django 5.0.3 on 2024-03-08 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0006_rename_week_scorer_num_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_app.player'),
        ),
    ]
