# Generated by Django 5.0.3 on 2024-03-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0009_alter_scorer_scorer_name_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scorer',
        ),
    ]
