# Generated by Django 5.0.3 on 2024-03-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0010_delete_scorer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='scored_at',
        ),
        migrations.AddField(
            model_name='goal',
            name='date',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
