# Generated by Django 5.0.3 on 2024-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0011_remove_goal_scored_at_goal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='class_year',
            field=models.IntegerField(default=2010, max_length=20),
        ),
    ]
