# Generated by Django 5.0.3 on 2024-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0015_alter_point_points_got'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='points_got',
            field=models.IntegerField(),
        ),
    ]
