# Generated by Django 5.0.3 on 2024-03-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0017_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='matches_played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_app.team'),
        ),
    ]
