# Generated by Django 5.0.3 on 2024-03-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0018_alter_table_matches_played_alter_table_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
